universe                = docker
docker_image            = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable              = run_pc_transfer.sh
output                  = runlogs/pc_transfer.$(ClusterId).out
error                   = runlogs/pc_transfer.$(ClusterId).err
log                     = runlogs/pc_transfer.$(ClusterId).log
should_transfer_files   = YES
request_GPUs            = 1
request_CPUs            = 8
request_memory          = 32G
requirements            = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted     = true
+WantScratchMounted     = true
stream_output = True
stream_error  = True
queue
